"""TỰ ĐỘNG SINH bởi tools/generate_catalog.py -- đừng sửa tay, chạy lại script.

Nguồn: Anuken/Mindustry (master, reference/*.java).
Bỏ qua 15 block không parse được (xem SKIPPED cuối file) -- không
phải bug, do cơ chế không khớp pattern hỗ trợ hoặc cố ý chưa model.
195 block khác chỉ lưu tên+category (GENERATED_OTHER) -- chưa có
recipe/rate, planner từ chối đặt thay vì đoán. Xem NEXT_STEPS.md.
"""

from .buildings import BuildingType, Item, Liquid, Recipe

GENERATED_ITEMS = {
    "beryllium": Item("beryllium", hardness=3, flammability=0.0),
    "blast-compound": Item("blast-compound", hardness=0, flammability=0.4),
    "carbide": Item("carbide", hardness=0, flammability=0.0),
    "coal": Item("coal", hardness=2, flammability=1.0),
    "copper": Item("copper", hardness=1, flammability=0.0),
    "dormant-cyst": Item("dormant-cyst", hardness=0, flammability=0.1),
    "fissile-matter": Item("fissile-matter", hardness=0, flammability=0.0),
    "graphite": Item("graphite", hardness=0, flammability=0.0),
    "lead": Item("lead", hardness=1, flammability=0.0),
    "metaglass": Item("metaglass", hardness=0, flammability=0.0),
    "oxide": Item("oxide", hardness=0, flammability=0.0),
    "phase-fabric": Item("phase-fabric", hardness=0, flammability=0.0),
    "plastanium": Item("plastanium", hardness=0, flammability=0.1),
    "pyratite": Item("pyratite", hardness=0, flammability=1.4),
    "sand": Item("sand", hardness=0, flammability=0.0),
    "scrap": Item("scrap", hardness=0, flammability=0.0),
    "silicon": Item("silicon", hardness=0, flammability=0.0),
    "spore-pod": Item("spore-pod", hardness=0, flammability=1.15),
    "surge-alloy": Item("surge-alloy", hardness=0, flammability=0.0),
    "thorium": Item("thorium", hardness=4, flammability=0.0),
    "titanium": Item("titanium", hardness=3, flammability=0.0),
    "tungsten": Item("tungsten", hardness=5, flammability=0.0),
}

GENERATED_LIQUIDS = {
    "arkycite": Liquid("arkycite"),
    "cryofluid": Liquid("cryofluid"),
    "cyanogen": Liquid("cyanogen"),
    "gallium": Liquid("gallium"),
    "hydrogen": Liquid("hydrogen"),
    "neoplasm": Liquid("neoplasm"),
    "nitrogen": Liquid("nitrogen"),
    "oil": Liquid("oil"),
    "ozone": Liquid("ozone"),
    "slag": Liquid("slag"),
    "water": Liquid("water"),
}

GENERATED_BUILDINGS = {
    "blast-drill": BuildingType("blast-drill", size=4, kind="drill", drill_time=280.0, hardness_multiplier=50.0, tier=5, power_input=180.0),
    "eruption-drill": BuildingType("eruption-drill", size=5, kind="drill", drill_time=281.25, hardness_multiplier=50.0, tier=7, power_input=360.0),
    "impact-drill": BuildingType("impact-drill", size=4, kind="drill", drill_time=720.0, hardness_multiplier=50.0, tier=6, power_input=160.0),
    "laser-drill": BuildingType("laser-drill", size=3, kind="drill", drill_time=280.0, hardness_multiplier=50.0, tier=4, power_input=66.0),
    "mechanical-drill": BuildingType("mechanical-drill", size=2, kind="drill", drill_time=600.0, hardness_multiplier=50.0, tier=2, power_input=0.0),
    "pneumatic-drill": BuildingType("pneumatic-drill", size=2, kind="drill", drill_time=400.0, hardness_multiplier=50.0, tier=3, power_input=0.0),
    "armored-conveyor": BuildingType("armored-conveyor", size=1, kind="belt", base_rate=10.0),
    "conveyor": BuildingType("conveyor", size=1, kind="belt", base_rate=6.5),
    "titanium-conveyor": BuildingType("titanium-conveyor", size=1, kind="belt", base_rate=10.0),
    "blast-mixer": BuildingType("blast-mixer", size=2, kind="factory", recipe=Recipe(craft_time=1.3333333333333333, inputs={"pyratite": 1.0, "spore-pod": 1.0}, liquid_inputs={}, output_item="blast-compound", output_amount=1), power_input=24.0),
    "graphite-press": BuildingType("graphite-press", size=2, kind="factory", recipe=Recipe(craft_time=1.5, inputs={"coal": 2.0}, liquid_inputs={}, output_item="graphite", output_amount=1), power_input=0.0),
    "kiln": BuildingType("kiln", size=2, kind="factory", recipe=Recipe(craft_time=0.5, inputs={"lead": 1.0, "sand": 1.0}, liquid_inputs={}, output_item="metaglass", output_amount=1), power_input=36.0),
    "multi-press": BuildingType("multi-press", size=3, kind="factory", recipe=Recipe(craft_time=0.5, inputs={"coal": 3.0}, liquid_inputs={"water": 3.0}, output_item="graphite", output_amount=2), power_input=108.0),
    "phase-weaver": BuildingType("phase-weaver", size=2, kind="factory", recipe=Recipe(craft_time=2.0, inputs={"thorium": 4.0, "sand": 10.0}, liquid_inputs={}, output_item="phase-fabric", output_amount=1), power_input=300.0),
    "plastanium-compressor": BuildingType("plastanium-compressor", size=2, kind="factory", recipe=Recipe(craft_time=1.0, inputs={"titanium": 2.0}, liquid_inputs={"oil": 15.0}, output_item="plastanium", output_amount=1), power_input=180.0),
    "pulverizer": BuildingType("pulverizer", size=1, kind="factory", recipe=Recipe(craft_time=0.6666666666666666, inputs={"scrap": 1.0}, liquid_inputs={}, output_item="sand", output_amount=1), power_input=30.0),
    "pyratite-mixer": BuildingType("pyratite-mixer", size=2, kind="factory", recipe=Recipe(craft_time=1.3333333333333333, inputs={"coal": 1.0, "lead": 2.0, "sand": 2.0}, liquid_inputs={}, output_item="pyratite", output_amount=1), power_input=12.0),
    "silicon-arc-furnace": BuildingType("silicon-arc-furnace", size=3, kind="factory", recipe=Recipe(craft_time=0.8333333333333334, inputs={"graphite": 1.0, "sand": 4.0}, liquid_inputs={}, output_item="silicon", output_amount=4), power_input=300.0),
    "silicon-smelter": BuildingType("silicon-smelter", size=2, kind="factory", recipe=Recipe(craft_time=0.6666666666666666, inputs={"coal": 1.0, "sand": 2.0}, liquid_inputs={}, output_item="silicon", output_amount=1), power_input=30.0),
    "slag-centrifuge": BuildingType("slag-centrifuge", size=3, kind="factory", recipe=Recipe(craft_time=2.0, inputs={"sand": 1.0}, liquid_inputs={"slag": 80.0}, output_item="scrap", output_amount=1), power_input=2.0),
    "surge-smelter": BuildingType("surge-smelter", size=3, kind="factory", recipe=Recipe(craft_time=1.25, inputs={"copper": 3.0, "lead": 4.0, "titanium": 2.0, "silicon": 3.0}, liquid_inputs={}, output_item="surge-alloy", output_amount=1), power_input=240.0),
    "inverted-sorter": BuildingType("inverted-sorter", size=1, kind="sorter", config_type="item", invert=True),
    "sorter": BuildingType("sorter", size=1, kind="sorter", config_type="item", invert=False),
    "impulse-pump": BuildingType("impulse-pump", size=3, kind="pump", pump_amount=0.22, power_input=78.0),
    "mechanical-pump": BuildingType("mechanical-pump", size=1, kind="pump", pump_amount=0.11666666666666667, power_input=0.0),
    "rotary-pump": BuildingType("rotary-pump", size=2, kind="pump", pump_amount=0.2, power_input=18.0),
    "conduit": BuildingType("conduit", size=1, kind="liquid-belt", base_rate=float("inf")),
    "plated-conduit": BuildingType("plated-conduit", size=1, kind="liquid-belt", base_rate=float("inf")),
    "pulse-conduit": BuildingType("pulse-conduit", size=1, kind="liquid-belt", base_rate=float("inf")),
    "reinforced-conduit": BuildingType("reinforced-conduit", size=1, kind="liquid-belt", base_rate=float("inf")),
    "distributor": BuildingType("distributor", size=2, kind="router"),
    "duct-router": BuildingType("duct-router", size=1, kind="router"),
    "liquid-container": BuildingType("liquid-container", size=2, kind="router"),
    "liquid-router": BuildingType("liquid-router", size=1, kind="router"),
    "liquid-tank": BuildingType("liquid-tank", size=3, kind="router"),
    "reinforced-liquid-container": BuildingType("reinforced-liquid-container", size=2, kind="router"),
    "reinforced-liquid-router": BuildingType("reinforced-liquid-router", size=1, kind="router"),
    "reinforced-liquid-tank": BuildingType("reinforced-liquid-tank", size=3, kind="router"),
    "router": BuildingType("router", size=1, kind="router"),
    "surge-router": BuildingType("surge-router", size=1, kind="router"),
    "junction": BuildingType("junction", size=1, kind="junction"),
    "liquid-junction": BuildingType("liquid-junction", size=1, kind="junction"),
    "reinforced-liquid-junction": BuildingType("reinforced-liquid-junction", size=1, kind="junction"),
    "overflow-duct": BuildingType("overflow-duct", size=1, kind="overflow-gate", invert=False),
    "overflow-gate": BuildingType("overflow-gate", size=1, kind="overflow-gate", invert=False),
    "underflow-duct": BuildingType("underflow-duct", size=1, kind="overflow-gate", invert=True),
    "underflow-gate": BuildingType("underflow-gate", size=1, kind="overflow-gate", invert=True),
    "bridge-conduit": BuildingType("bridge-conduit", size=1, kind="bridge", link_range=4),
    "bridge-conveyor": BuildingType("bridge-conveyor", size=1, kind="bridge", link_range=4),
    "duct-bridge": BuildingType("duct-bridge", size=1, kind="bridge", link_range=4),
    "phase-conduit": BuildingType("phase-conduit", size=1, kind="bridge", link_range=12),
    "phase-conveyor": BuildingType("phase-conveyor", size=1, kind="bridge", link_range=12),
    "reinforced-bridge-conduit": BuildingType("reinforced-bridge-conduit", size=1, kind="bridge", link_range=4),
    "mass-driver": BuildingType("mass-driver", size=3, kind="mass-driver", driver_capacity=120.0, driver_reload=200.0, link_range=55.0),
    "duct-unloader": BuildingType("duct-unloader", size=1, kind="unloader", base_rate=15.0, config_type="item"),
    "unloader": BuildingType("unloader", size=1, kind="unloader", base_rate=11.0, config_type="item"),
    "container": BuildingType("container", size=2, kind="storage"),
    "reinforced-container": BuildingType("reinforced-container", size=2, kind="storage"),
    "reinforced-vault": BuildingType("reinforced-vault", size=3, kind="storage"),
    "vault": BuildingType("vault", size=3, kind="storage"),
    "combustion-generator": BuildingType("combustion-generator", size=1, kind="generator", power_production=1.0, item_duration=120.0, min_flammability=0.2, generator_liquid_inputs={}),
    "steam-generator": BuildingType("steam-generator", size=2, kind="generator", power_production=5.5, item_duration=90.0, min_flammability=0.2, generator_liquid_inputs={"water": 9.0}),
    "power-node": BuildingType("power-node", size=1, kind="power-node", power_range=6.0),
    "power-node-large": BuildingType("power-node-large", size=2, kind="power-node", power_range=15.0),
    "surge-tower": BuildingType("surge-tower", size=2, kind="power-node", power_range=40.0),
}

# Chỉ có tên+category+size, CHƯA có recipe/rate -- planner từ chối đặt
# loại này thay vì đoán. Xem NEXT_STEPS.md mục "Phạm vi chưa làm".
GENERATED_OTHER = {
    "additive-reconstructor": BuildingType("additive-reconstructor", size=3, kind="units", category="units"),
    "advanced-launch-pad": BuildingType("advanced-launch-pad", size=4, kind="effect", category="effect"),
    "afflict": BuildingType("afflict", size=4, kind="turret", category="turret"),
    "air-factory": BuildingType("air-factory", size=3, kind="units", category="units"),
    "arc": BuildingType("arc", size=1, kind="turret", category="turret"),
    "armored-duct": BuildingType("armored-duct", size=1, kind="distribution", category="distribution"),
    "atmospheric-concentrator": BuildingType("atmospheric-concentrator", size=3, kind="crafting", category="crafting"),
    "basic-assembler-module": BuildingType("basic-assembler-module", size=5, kind="units", category="units"),
    "battery": BuildingType("battery", size=1, kind="power", category="power"),
    "battery-large": BuildingType("battery-large", size=3, kind="power", category="power"),
    "beam-link": BuildingType("beam-link", size=3, kind="power", category="power"),
    "beam-node": BuildingType("beam-node", size=1, kind="power", category="power"),
    "beam-tower": BuildingType("beam-tower", size=3, kind="power", category="power"),
    "beryllium-wall": BuildingType("beryllium-wall", size=1, kind="defense", category="defense"),
    "beryllium-wall-large": BuildingType("beryllium-wall-large", size=2, kind="defense", category="defense"),
    "blast-door": BuildingType("blast-door", size=2, kind="defense", category="defense"),
    "breach": BuildingType("breach", size=3, kind="turret", category="turret"),
    "build-tower": BuildingType("build-tower", size=3, kind="effect", category="effect"),
    "canvas": BuildingType("canvas", size=2, kind="logic", category="logic"),
    "carbide-crucible": BuildingType("carbide-crucible", size=3, kind="crafting", category="crafting"),
    "carbide-wall": BuildingType("carbide-wall", size=1, kind="defense", category="defense"),
    "carbide-wall-large": BuildingType("carbide-wall-large", size=2, kind="defense", category="defense"),
    "chemical-combustion-chamber": BuildingType("chemical-combustion-chamber", size=3, kind="power", category="power"),
    "cliff-crusher": BuildingType("cliff-crusher", size=2, kind="production", category="production"),
    "coal-centrifuge": BuildingType("coal-centrifuge", size=2, kind="crafting", category="crafting"),
    "constructor": BuildingType("constructor", size=3, kind="units", category="units"),
    "copper-wall": BuildingType("copper-wall", size=1, kind="defense", category="defense"),
    "copper-wall-large": BuildingType("copper-wall-large", size=2, kind="defense", category="defense"),
    "core-acropolis": BuildingType("core-acropolis", size=6, kind="effect", category="effect"),
    "core-bastion": BuildingType("core-bastion", size=4, kind="effect", category="effect"),
    "core-citadel": BuildingType("core-citadel", size=5, kind="effect", category="effect"),
    "core-foundation": BuildingType("core-foundation", size=4, kind="effect", category="effect"),
    "core-nucleus": BuildingType("core-nucleus", size=5, kind="effect", category="effect"),
    "core-shard": BuildingType("core-shard", size=3, kind="effect", category="effect"),
    "cryofluid-mixer": BuildingType("cryofluid-mixer", size=2, kind="crafting", category="crafting"),
    "cultivator": BuildingType("cultivator", size=2, kind="production", category="production"),
    "cyanogen-synthesizer": BuildingType("cyanogen-synthesizer", size=3, kind="crafting", category="crafting"),
    "cyclone": BuildingType("cyclone", size=3, kind="turret", category="turret"),
    "deconstructor": BuildingType("deconstructor", size=5, kind="units", category="units"),
    "differential-generator": BuildingType("differential-generator", size=3, kind="power", category="power"),
    "diffuse": BuildingType("diffuse", size=3, kind="turret", category="turret"),
    "diode": BuildingType("diode", size=1, kind="power", category="power"),
    "disassembler": BuildingType("disassembler", size=3, kind="crafting", category="crafting"),
    "disperse": BuildingType("disperse", size=4, kind="turret", category="turret"),
    "door": BuildingType("door", size=1, kind="defense", category="defense"),
    "door-large": BuildingType("door-large", size=2, kind="defense", category="defense"),
    "duct": BuildingType("duct", size=1, kind="distribution", category="distribution"),
    "duo": BuildingType("duo", size=1, kind="turret", category="turret"),
    "electric-heater": BuildingType("electric-heater", size=2, kind="crafting", category="crafting"),
    "electrolyzer": BuildingType("electrolyzer", size=3, kind="crafting", category="crafting"),
    "exponential-reconstructor": BuildingType("exponential-reconstructor", size=7, kind="units", category="units"),
    "flux-reactor": BuildingType("flux-reactor", size=5, kind="power", category="power"),
    "force-projector": BuildingType("force-projector", size=3, kind="effect", category="effect"),
    "foreshadow": BuildingType("foreshadow", size=4, kind="turret", category="turret"),
    "fuse": BuildingType("fuse", size=3, kind="turret", category="turret"),
    "ground-factory": BuildingType("ground-factory", size=3, kind="units", category="units"),
    "hail": BuildingType("hail", size=1, kind="turret", category="turret"),
    "heat-reactor": BuildingType("heat-reactor", size=3, kind="crafting", category="crafting"),
    "heat-redirector": BuildingType("heat-redirector", size=3, kind="crafting", category="crafting"),
    "heat-router": BuildingType("heat-router", size=3, kind="crafting", category="crafting"),
    "heat-source": BuildingType("heat-source", size=1, kind="crafting", category="crafting"),
    "hyper-processor": BuildingType("hyper-processor", size=3, kind="logic", category="logic"),
    "illuminator": BuildingType("illuminator", size=1, kind="effect", category="effect"),
    "impact-reactor": BuildingType("impact-reactor", size=4, kind="power", category="power"),
    "incinerator": BuildingType("incinerator", size=1, kind="crafting", category="crafting"),
    "interplanetary-accelerator": BuildingType("interplanetary-accelerator", size=7, kind="effect", category="effect"),
    "item-source": BuildingType("item-source", size=1, kind="distribution", category="distribution"),
    "item-void": BuildingType("item-void", size=1, kind="distribution", category="distribution"),
    "lancer": BuildingType("lancer", size=2, kind="turret", category="turret"),
    "landing-pad": BuildingType("landing-pad", size=4, kind="effect", category="effect"),
    "large-canvas": BuildingType("large-canvas", size=3, kind="logic", category="logic"),
    "large-cliff-crusher": BuildingType("large-cliff-crusher", size=3, kind="production", category="production"),
    "large-constructor": BuildingType("large-constructor", size=5, kind="units", category="units"),
    "large-logic-display": BuildingType("large-logic-display", size=6, kind="logic", category="logic"),
    "large-payload-mass-driver": BuildingType("large-payload-mass-driver", size=5, kind="units", category="units"),
    "large-plasma-bore": BuildingType("large-plasma-bore", size=3, kind="production", category="production"),
    "large-shield-projector": BuildingType("large-shield-projector", size=4, kind="effect", category="effect"),
    "launch-pad": BuildingType("launch-pad", size=3, kind="effect", category="effect"),
    "liquid-source": BuildingType("liquid-source", size=1, kind="liquid", category="liquid"),
    "liquid-void": BuildingType("liquid-void", size=1, kind="liquid", category="liquid"),
    "logic-display": BuildingType("logic-display", size=3, kind="logic", category="logic"),
    "logic-processor": BuildingType("logic-processor", size=2, kind="logic", category="logic"),
    "lustre": BuildingType("lustre", size=4, kind="turret", category="turret"),
    "malign": BuildingType("malign", size=5, kind="turret", category="turret"),
    "mech-assembler": BuildingType("mech-assembler", size=5, kind="units", category="units"),
    "mech-fabricator": BuildingType("mech-fabricator", size=3, kind="units", category="units"),
    "mech-refabricator": BuildingType("mech-refabricator", size=3, kind="units", category="units"),
    "meltdown": BuildingType("meltdown", size=4, kind="turret", category="turret"),
    "melter": BuildingType("melter", size=1, kind="crafting", category="crafting"),
    "memory-bank": BuildingType("memory-bank", size=2, kind="logic", category="logic"),
    "memory-cell": BuildingType("memory-cell", size=1, kind="logic", category="logic"),
    "mend-projector": BuildingType("mend-projector", size=2, kind="effect", category="effect"),
    "mender": BuildingType("mender", size=1, kind="effect", category="effect"),
    "message": BuildingType("message", size=1, kind="logic", category="logic"),
    "micro-processor": BuildingType("micro-processor", size=1, kind="logic", category="logic"),
    "multiplicative-reconstructor": BuildingType("multiplicative-reconstructor", size=5, kind="units", category="units"),
    "naval-factory": BuildingType("naval-factory", size=3, kind="units", category="units"),
    "neoplasia-reactor": BuildingType("neoplasia-reactor", size=5, kind="power", category="power"),
    "oil-extractor": BuildingType("oil-extractor", size=3, kind="production", category="production"),
    "overdrive-dome": BuildingType("overdrive-dome", size=3, kind="effect", category="effect"),
    "overdrive-projector": BuildingType("overdrive-projector", size=2, kind="effect", category="effect"),
    "oxidation-chamber": BuildingType("oxidation-chamber", size=3, kind="crafting", category="crafting"),
    "parallax": BuildingType("parallax", size=2, kind="turret", category="turret"),
    "payload-conveyor": BuildingType("payload-conveyor", size=1, kind="units", category="units"),
    "payload-loader": BuildingType("payload-loader", size=3, kind="units", category="units"),
    "payload-mass-driver": BuildingType("payload-mass-driver", size=3, kind="units", category="units"),
    "payload-router": BuildingType("payload-router", size=1, kind="units", category="units"),
    "payload-source": BuildingType("payload-source", size=5, kind="units", category="units"),
    "payload-unloader": BuildingType("payload-unloader", size=3, kind="units", category="units"),
    "payload-void": BuildingType("payload-void", size=5, kind="units", category="units"),
    "phase-heater": BuildingType("phase-heater", size=2, kind="crafting", category="crafting"),
    "phase-synthesizer": BuildingType("phase-synthesizer", size=3, kind="crafting", category="crafting"),
    "phase-wall": BuildingType("phase-wall", size=1, kind="defense", category="defense"),
    "phase-wall-large": BuildingType("phase-wall-large", size=2, kind="defense", category="defense"),
    "plasma-bore": BuildingType("plasma-bore", size=2, kind="production", category="production"),
    "plastanium-conveyor": BuildingType("plastanium-conveyor", size=1, kind="distribution", category="distribution"),
    "plastanium-wall": BuildingType("plastanium-wall", size=1, kind="defense", category="defense"),
    "plastanium-wall-large": BuildingType("plastanium-wall-large", size=2, kind="defense", category="defense"),
    "power-source": BuildingType("power-source", size=1, kind="power", category="power"),
    "power-void": BuildingType("power-void", size=1, kind="power", category="power"),
    "prime-refabricator": BuildingType("prime-refabricator", size=5, kind="units", category="units"),
    "pyrolysis-generator": BuildingType("pyrolysis-generator", size=3, kind="power", category="power"),
    "radar": BuildingType("radar", size=1, kind="effect", category="effect"),
    "regen-projector": BuildingType("regen-projector", size=3, kind="effect", category="effect"),
    "reinforced-message": BuildingType("reinforced-message", size=1, kind="logic", category="logic"),
    "reinforced-payload-conveyor": BuildingType("reinforced-payload-conveyor", size=1, kind="units", category="units"),
    "reinforced-payload-router": BuildingType("reinforced-payload-router", size=1, kind="units", category="units"),
    "reinforced-pump": BuildingType("reinforced-pump", size=2, kind="liquid", category="liquid"),
    "reinforced-surge-wall": BuildingType("reinforced-surge-wall", size=1, kind="defense", category="defense"),
    "reinforced-surge-wall-large": BuildingType("reinforced-surge-wall-large", size=2, kind="defense", category="defense"),
    "repair-point": BuildingType("repair-point", size=1, kind="units", category="units"),
    "repair-turret": BuildingType("repair-turret", size=2, kind="units", category="units"),
    "ripple": BuildingType("ripple", size=3, kind="turret", category="turret"),
    "rtg-generator": BuildingType("rtg-generator", size=2, kind="power", category="power"),
    "salvo": BuildingType("salvo", size=2, kind="turret", category="turret"),
    "scathe": BuildingType("scathe", size=4, kind="turret", category="turret"),
    "scatter": BuildingType("scatter", size=2, kind="turret", category="turret"),
    "scorch": BuildingType("scorch", size=1, kind="turret", category="turret"),
    "scrap-wall": BuildingType("scrap-wall", size=1, kind="defense", category="defense"),
    "scrap-wall-gigantic": BuildingType("scrap-wall-gigantic", size=4, kind="defense", category="defense"),
    "scrap-wall-huge": BuildingType("scrap-wall-huge", size=3, kind="defense", category="defense"),
    "scrap-wall-large": BuildingType("scrap-wall-large", size=2, kind="defense", category="defense"),
    "segment": BuildingType("segment", size=2, kind="turret", category="turret"),
    "separator": BuildingType("separator", size=2, kind="crafting", category="crafting"),
    "shield-projector": BuildingType("shield-projector", size=3, kind="effect", category="effect"),
    "shielded-wall": BuildingType("shielded-wall", size=2, kind="defense", category="defense"),
    "ship-assembler": BuildingType("ship-assembler", size=5, kind="units", category="units"),
    "ship-fabricator": BuildingType("ship-fabricator", size=3, kind="units", category="units"),
    "ship-refabricator": BuildingType("ship-refabricator", size=3, kind="units", category="units"),
    "shock-mine": BuildingType("shock-mine", size=1, kind="effect", category="effect"),
    "shockwave-tower": BuildingType("shockwave-tower", size=3, kind="effect", category="effect"),
    "silicon-crucible": BuildingType("silicon-crucible", size=3, kind="crafting", category="crafting"),
    "slag-heater": BuildingType("slag-heater", size=3, kind="crafting", category="crafting"),
    "slag-incinerator": BuildingType("slag-incinerator", size=1, kind="crafting", category="crafting"),
    "small-deconstructor": BuildingType("small-deconstructor", size=3, kind="units", category="units"),
    "small-heat-redirector": BuildingType("small-heat-redirector", size=2, kind="crafting", category="crafting"),
    "smite": BuildingType("smite", size=5, kind="turret", category="turret"),
    "solar-panel": BuildingType("solar-panel", size=1, kind="power", category="power"),
    "solar-panel-large": BuildingType("solar-panel-large", size=3, kind="power", category="power"),
    "spectre": BuildingType("spectre", size=4, kind="turret", category="turret"),
    "spore-press": BuildingType("spore-press", size=2, kind="crafting", category="crafting"),
    "sublimate": BuildingType("sublimate", size=3, kind="turret", category="turret"),
    "surge-conveyor": BuildingType("surge-conveyor", size=1, kind="distribution", category="distribution"),
    "surge-crucible": BuildingType("surge-crucible", size=3, kind="crafting", category="crafting"),
    "surge-wall": BuildingType("surge-wall", size=1, kind="defense", category="defense"),
    "surge-wall-large": BuildingType("surge-wall-large", size=2, kind="defense", category="defense"),
    "swarmer": BuildingType("swarmer", size=2, kind="turret", category="turret"),
    "switch": BuildingType("switch", size=1, kind="logic", category="logic"),
    "tank-assembler": BuildingType("tank-assembler", size=5, kind="units", category="units"),
    "tank-fabricator": BuildingType("tank-fabricator", size=3, kind="units", category="units"),
    "tank-refabricator": BuildingType("tank-refabricator", size=3, kind="units", category="units"),
    "tetrative-reconstructor": BuildingType("tetrative-reconstructor", size=9, kind="units", category="units"),
    "thermal-generator": BuildingType("thermal-generator", size=2, kind="power", category="power"),
    "thorium-reactor": BuildingType("thorium-reactor", size=3, kind="power", category="power"),
    "thorium-wall": BuildingType("thorium-wall", size=1, kind="defense", category="defense"),
    "thorium-wall-large": BuildingType("thorium-wall-large", size=2, kind="defense", category="defense"),
    "thruster": BuildingType("thruster", size=4, kind="defense", category="defense"),
    "tile-logic-display": BuildingType("tile-logic-display", size=1, kind="logic", category="logic"),
    "titan": BuildingType("titan", size=4, kind="turret", category="turret"),
    "titanium-wall": BuildingType("titanium-wall", size=1, kind="defense", category="defense"),
    "titanium-wall-large": BuildingType("titanium-wall-large", size=2, kind="defense", category="defense"),
    "tsunami": BuildingType("tsunami", size=3, kind="turret", category="turret"),
    "tungsten-wall": BuildingType("tungsten-wall", size=1, kind="defense", category="defense"),
    "tungsten-wall-large": BuildingType("tungsten-wall-large", size=2, kind="defense", category="defense"),
    "turbine-condenser": BuildingType("turbine-condenser", size=3, kind="power", category="power"),
    "unit-cargo-loader": BuildingType("unit-cargo-loader", size=3, kind="distribution", category="distribution"),
    "unit-cargo-unload-point": BuildingType("unit-cargo-unload-point", size=2, kind="distribution", category="distribution"),
    "unit-repair-tower": BuildingType("unit-repair-tower", size=2, kind="units", category="units"),
    "vent-condenser": BuildingType("vent-condenser", size=3, kind="production", category="production"),
    "water-extractor": BuildingType("water-extractor", size=2, kind="production", category="production"),
    "wave": BuildingType("wave", size=2, kind="turret", category="turret"),
    "world-cell": BuildingType("world-cell", size=1, kind="logic", category="logic"),
    "world-message": BuildingType("world-message", size=1, kind="logic", category="logic"),
    "world-processor": BuildingType("world-processor", size=1, kind="logic", category="logic"),
    "world-switch": BuildingType("world-switch", size=1, kind="logic", category="logic"),
}

SKIPPED = [
    ("cryofluid-mixer", "GenericCrafter", "thiếu/không parse được outputItem"),
    ("melter", "GenericCrafter", "thiếu/không parse được outputItem"),
    ("spore-press", "GenericCrafter", "thiếu/không parse được outputItem"),
    ("coal-centrifuge", "GenericCrafter", "thiếu/không parse được input item (có thể chỉ dùng liquid/power)"),
    ("electrolyzer", "GenericCrafter", "thiếu/không parse được outputItem"),
    ("reinforced-pump", "Pump", "pump tự tiêu thụ liquid (vd reinforced-pump) -- chưa model"),
    ("differential-generator", "ConsumeGenerator", "không dùng ConsumeItemFlammable (vd dựa nhiệt độ/tile) -- cơ chế khác, chưa model"),
    ("rtg-generator", "ConsumeGenerator", "không dùng ConsumeItemFlammable (vd dựa nhiệt độ/tile) -- cơ chế khác, chưa model"),
    ("chemical-combustion-chamber", "ConsumeGenerator", "không dùng ConsumeItemFlammable (vd dựa nhiệt độ/tile) -- cơ chế khác, chưa model"),
    ("pyrolysis-generator", "ConsumeGenerator", "không dùng ConsumeItemFlammable (vd dựa nhiệt độ/tile) -- cơ chế khác, chưa model"),
    ("plastanium-conveyor", "StackConveyor", "cơ chế xếp chồng nhiều item/ô, khác hẳn Conveyor thường"),
    ("surge-conveyor", "StackConveyor", "cơ chế xếp chồng nhiều item/ô, khác hẳn Conveyor thường"),
    ("water-extractor", "SolidPump", "rút 1 liquid cố định bất kể tile, không cần liquid tile khớp như Pump"),
    ("plasma-bore", "BeamDrill", "đào theo tia dọc 1 hướng (range), không phải diện tích chân đế như Drill"),
    ("large-plasma-bore", "BeamDrill", "đào theo tia dọc 1 hướng (range), không phải diện tích chân đế như Drill"),
]
